sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t weyombo/docker-react -f dockerfile.dev .

script:
  - docker run weyombo/docker-react npm run test -- --coverage
